name: Show Error

on:
  push:

jobs:
  build-and-run:
    name: Build
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          # needed for 'pre-commit-mirrors-insert-license'
          fetch-depth: 0
          - name: Set up Docker Builddockx
        uses: docker/setup-buildx-action@v2
